# Generated by Django 5.1.6 on 2025-03-24 12:28

import functools
import imagekit.models.fields
import wosvcore.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Passive')], default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('background', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'field_name': 'title', 'upload_to': 'banners'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Background Image')),
                ('left_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'field_name': 'title', 'upload_to': 'banners/left'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Left Image')),
                ('right_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'field_name': 'title', 'upload_to': 'banners/right'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Right Image')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='storycategories',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'field_name': 'title', 'upload_to': 'story_categories'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Page Image'),
        ),
    ]
