# Generated by Django 5.1.6 on 2025-03-24 12:46

import functools
import imagekit.models.fields
import wosvcore.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banners_alter_storycategories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='left_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'custom_prefix': 'left-image', 'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Left Image'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='right_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'custom_prefix': 'right-image', 'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Left Image'),
        ),
    ]
