# Generated by Django 5.1.6 on 2025-04-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_banners_left_image_alter_banners_right_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='storycategories',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='storycategories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='storycategories',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='storycategories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
