# Generated by Django 5.1.6 on 2025-03-24 10:09

import django.db.models.deletion
import mptt.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Passive')], default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Content')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='pages/')),
                ('alt_url', models.URLField(blank=True, null=True, verbose_name='Alternative URL')),
                ('visible_home', models.BooleanField(default=False, verbose_name='Visible on Homepage')),
                ('visible_header', models.BooleanField(default=False, verbose_name='Visible in Header')),
                ('visible_footer', models.BooleanField(default=False, verbose_name='Visible in Footer')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('faq', 'FAQ'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=40, verbose_name='Page Type')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.pages', verbose_name='Parent Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Passive')], default=True, verbose_name='Status')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', tinymce.models.HTMLField(blank=True, verbose_name='Content')),
                ('image_path', models.ImageField(blank=True, null=True, upload_to='contents/')),
                ('alt_url', models.URLField(blank=True, null=True, verbose_name='Alternative URL')),
                ('visible_home', models.BooleanField(default=False, verbose_name='Visible on Homepage')),
                ('video_type', models.CharField(choices=[('youtube', 'Youtube'), ('vimeo', 'Vimeo')], max_length=50, verbose_name='Video Type')),
                ('video_url', models.URLField(verbose_name='Video URL')),
                ('video_thumb_url', models.URLField(blank=True, null=True, verbose_name='Video Thumbnail URL')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('card', 'Card'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('link', 'Link'), ('accordion', 'Accordion'), ('tab_segment', 'Tab Segment')], max_length=50, verbose_name='Content Type')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.contents', verbose_name='Parent Content')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pages', verbose_name='Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
