# Generated by Django 5.1.6 on 2025-03-24 12:28

import functools
import imagekit.models.fields
import wosvcore.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='header_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'custom_prefix': 'header-image', 'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Header Image'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='image_path',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Page Image'),
        ),
    ]
