# Generated by Django 5.1.6 on 2025-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_pages_page_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='page_type',
            field=models.CharField(choices=[('page', 'Sayfa'), ('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('stories', 'Stories'), ('faq', 'FAQ'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], max_length=40, verbose_name='Page Type'),
        ),
    ]
