# Generated by Django 5.1.6 on 2025-04-08 18:39

import functools
import imagekit.models.fields
import wosvcore.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pages_page_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=50, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image_path', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'custom_prefix': 'page-image', 'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contents',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='pages',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('card', 'Card'), ('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('link', 'Link'), ('accordion', 'Accordion'), ('tab_segment', 'Tab Segment')], default=('text', 'Text'), max_length=50, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='image_path',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=functools.partial(wosvcore.utils.generate_unique_filename, *(), **{'custom_prefix': 'content-image', 'field_name': 'title', 'upload_to': 'pages'}), validators=[wosvcore.utils.validate_file_extension], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_type',
            field=models.CharField(choices=[('page', 'Sayfa'), ('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('stories', 'Stories'), ('faq', 'FAQ'), ('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy')], default=('page', 'Sayfa'), max_length=40, verbose_name='Page Type'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('published', 'Published'), ('draft', 'Draft')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
