# Generated by Django 5.1.6 on 2025-02-12 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('topic', models.CharField(max_length=200, verbose_name='Konu')),
                ('scene_count', models.PositiveIntegerField(default=1, verbose_name='Sahne Sayısı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('content', models.TextField(blank=True, null=True, verbose_name='İçerik')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sahne Başlığı')),
                ('scene_number', models.PositiveIntegerField(default=1, verbose_name='Sahne Numarası')),
                ('content', models.TextField(blank=True, null=True, verbose_name='İçerik')),
                ('gen_content', models.TextField(blank=True, null=True, verbose_name='Oluşturma Promptu')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated_images/', verbose_name='Oluşturulan Resim')),
                ('image', models.ImageField(blank=True, null=True, upload_to='scenes/', verbose_name='Resim')),
                ('keyword', models.CharField(blank=True, max_length=200, null=True, verbose_name='Anahtar Kelime')),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='Soru')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.stories')),
            ],
            options={
                'verbose_name_plural': 'Scenes',
                'ordering': ['scene_number'],
            },
        ),
    ]
