# Generated by Django 5.1.6 on 2025-02-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('in_review', 'In Review'), ('needs_revision', 'Needs Revision'), ('completed', 'Completed'), ('published', 'Published')], default='draft', max_length=50, verbose_name='Durum'),
        ),
    ]
