# Generated by Django 5.1.6 on 2025-02-14 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_stories_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenes',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.stories', verbose_name='Hikaye'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('needs_revision', 'Needs Revision'), ('completed', 'Completed'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=50, verbose_name='Durum'),
        ),
    ]
