# Generated by Django 5.1.6 on 2025-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_scenes_story_alter_stories_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenes',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Resim URL'),
        ),
    ]
