# Generated by Django 5.1.6 on 2025-03-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_scenes_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scenes',
            old_name='image',
            new_name='scene_image',
        ),
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('completed', 'Completed'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='draft', max_length=50, verbose_name='Durum'),
        ),
    ]
