# Generated by Django 5.1.6 on 2025-03-24 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_rename_image_scenes_scene_image_alter_stories_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenes',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='gen_content',
            field=models.TextField(blank=True, null=True, verbose_name='Generate Content'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='generated_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_images/', verbose_name='Generated Image'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='image_url',
            field=models.TextField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='question',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='scene_image',
            field=models.ImageField(blank=True, null=True, upload_to='scenes/', verbose_name='Scene Image'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='scene_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Scene Number'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='scene_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Scene Title'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='stories.stories', verbose_name='Story'),
        ),
        migrations.AlterField(
            model_name='scenes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='scene_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Scenes'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_process', 'In Process'), ('completed', 'Completed'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='draft', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='topic',
            field=models.CharField(max_length=200, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
