# Generated by Django 5.1.6 on 2025-04-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_scenes_content_alter_scenes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='stories/', verbose_name='Cover Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stories',
            name='story_image',
            field=models.ImageField(default=1, upload_to='stories/', verbose_name='Story Image'),
            preserve_default=False,
        ),
    ]
